import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { login } from '../services/authApi.js';
import '../styles/auth.css';
const ROLES={owner:{label:'Owner',icon:'bi-person-badge',title:'Run your workshop with clarity.',text:'Manage jobs, designs, team assignments and production from one workspace.'},karigar:{label:'Karigar',icon:'bi-hammer',title:'Know what needs your hands next.',text:'See assigned jobs, deadlines and production updates from your workshop.'}};
export default function Login({onLogin}){
 const navigate=useNavigate();
 const [role,setRole]=useState('owner'),[workshopCode,setWorkshopCode]=useState(''),[phone,setPhone]=useState(''),[pin,setPin]=useState(''),[show,setShow]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e){e.preventDefault();setError('');const p=phone.replace(/\D/g,'');if(role==='karigar' && !workshopCode.trim())return setError('Enter your workshop code.');if(p.length!==10)return setError('Enter a valid 10-digit phone number.');if(!pin)return setError('Enter your PIN to continue.');setBusy(true);try{const r=await login(p,pin,role,workshopCode.trim());if(!r?.user?.workshop_id)throw new Error('This account is not linked to a workspace.');onLogin(r);navigate(r.user.role==='owner'?'/owner':'/karigar')}catch(err){setError(err?.message||'We could not sign you in. Please check your details.')}finally{setBusy(false)}}
 const c=ROLES[role];
 return <div className="wl-auth-v2 wl-login-v2"><section className="wl-auth-v2-visual"><Link to="/" className="wl-auth-v2-brand"><img src="/logo-mark.png" alt="Workloom"/><span><small>JEWELLERY WORKFLOWS, WOVEN BETTER</small><strong>WORKLOOM</strong></span></Link><div className="wl-auth-v2-story"><span className="wl-auth-v2-kicker"><i/> EXISTING WORKSPACE</span><h1>{c.title}</h1><p>{c.text}</p></div><div className="wl-auth-v2-meta"><span><i className="bi bi-shield-check"/> Workspace-protected access</span><span><i className="bi bi-diagram-3"/> Role-based access</span></div><div className="wl-auth-v2-orbit" aria-hidden="true"><span/><span/><span/></div></section><section className="wl-auth-v2-panel"><div className="wl-auth-v2-card"><Link to="/" className="wl-auth-v2-back"><i className="bi bi-arrow-left"/> Back to Workloom</Link><div className="wl-auth-v2-heading"><span className="wl-auth-v2-step">SIGN IN</span><h2>Welcome back.</h2><p>Use the credentials of your existing workspace account.</p></div><div className="wl-auth-v2-roles">{Object.entries(ROLES).map(([k,v])=><button key={k} type="button" className={role===k?'active':''} onClick={()=>{setRole(k);setError('')}}><i className={`bi ${v.icon}`}/>{v.label}</button>)}</div><form onSubmit={submit} className="wl-auth-v2-form">{error&&<div className="wl-auth-v2-error"><i className="bi bi-exclamation-circle"/><span>{error}</span></div>}{role==='karigar'&&<><label>Workshop code</label><div className="wl-auth-v2-input"><i className="bi bi-building"/><input type="text" value={workshopCode} onChange={e=>setWorkshopCode(e.target.value.toUpperCase())} placeholder="e.g. WL-A1B2C3" autoComplete="organization"/></div></>}<label>Phone number</label><div className="wl-auth-v2-input"><i className="bi bi-phone"/><input type="tel" inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="98765 43210" autoComplete="username" maxLength={14}/></div><label>PIN</label><div className="wl-auth-v2-input"><i className="bi bi-lock"/><input type={show?'text':'password'} value={pin} onChange={e=>setPin(e.target.value)} placeholder="Enter your PIN" autoComplete="current-password"/><button type="button" onClick={()=>setShow(v=>!v)} aria-label={show?'Hide PIN':'Show PIN'}><i className={`bi ${show?'bi-eye-slash':'bi-eye'}`}/></button></div><button className="wl-auth-v2-submit" disabled={busy}>{busy? 'Checking workspace…':`Continue as ${c.label}`}<i className="bi bi-arrow-right"/></button></form><div className="wl-auth-v2-create"><div><span>NEW TO WORKLOOM?</span><strong>Create your workshop workspace first.</strong></div><Link to="/register-owner">Create workspace <i className="bi bi-arrow-up-right"/></Link></div></div></section></div>;
}
